Repository module-federation/module-federation-examples, pull requests merged in 2023-10, with the labels that each got.

#3181 chore(deps): pin dependency lerna to v7.1.5
  package.json
Labels: workflow-failure

#3182 chore(deps): update dependency @module-federation/dashboard-plugin to v2.7.5
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-delegate-example/utils/package.json
Labels: workflow-failure

#3187 chore(deps): update dependency @swc-node/register to v1.6.8
  medusa-nx-native-federation-example/package-lock.json
  medusa-nx-native-federation-example/package.json
  medusa-nx-native-federation-example/yarn.lock
Labels: workflow-cancelled

#3184 chore(deps): update dependency @pmmmwh/react-refresh-webpack-plugin to v0.5.11
  react-hmr/remote1/package.json
Labels: workflow-failure

#3233 fix: e2e test
  advanced-api/automatic-vendor-sharing/lerna.json
  advanced-api/dynamic-remotes-runtime-environment-variables/lerna.json
  advanced-api/dynamic-remotes-synchronous-imports/lerna.json
  advanced-api/dynamic-remotes/lerna.json
  basic-host-remote/app1/src/routes/page.jsx
  basic-host-remote/app2/src/routes/page.jsx
  comprehensive-demo-react16/lerna.json
  cra/lerna.json
  css-isolation/lerna.json
  different-react-versions-isolated/lerna.json
  different-react-versions/lerna.json
  dynamic-system-host/lerna.json
  native-federation-tests-typescript-plugins/lerna.json
  nested/lerna.json
  react-in-vue/lerna.json
  redux-reducer-injection/lerna.json
  self-healing/lerna.json
  shared-context/lerna.json
  shared-routes2/lerna.json
  shared-routing/lerna.json
  shared-store-cross-framework/lerna.json
  startup-code/lerna.json
  typescript-project-references/lerna.json
  typescript-react-fallback/lerna.json
  typescript/lerna.json
  version-discrepancy/lerna.json
  vue2-in-vue3/lerna.json
  vue3-demo/lerna.json
Labels: workflow-failure

#3223 ysys
  package.json
Labels: workflow-failure

#3242 chore(deps): update dependency cypress-real-events to v1.10.3
  package.json
Labels: workflow-failure

#3237 chore(deps): update dependency concurrently to v7.6.0
  react-storybook/package.json
Labels: workflow-failure

#3265 fix: cli.isMultipleCompiler is not a function
  different-react-versions-16-17-typescript/app1/package.json
  different-react-versions-16-17-typescript/app2/package.json
  different-react-versions-16-17/app1/package.json
  different-react-versions-16-17/app2/package.json
  different-react-versions-16-18/app1/package.json
  different-react-versions-16-18/app2/package.json
  different-react-versions-typescript/app1/package.json
  different-react-versions-typescript/app2/package.json
Labels: workflow-failure

#3266 fix: add e2e test missed deps/config
  comprehensive-demo-react16/app-04/webpack.config.js
  comprehensive-demo-react18/app-04/webpack.config.js
  comprehensive-demo-react18/lerna.json
  comprehensive-demo-react18/package.json
  delegate-modules/package.json
  different-react-versions-typescript/package.json
  dynamic-system-host/app1/webpack.config.js
Labels: workflow-failure

#3192 chore(deps): update dependency @types/react to v16.14.50
  different-react-versions-16-17-typescript/app1/package.json
  different-react-versions-16-18-typescript/app1/package.json
  different-react-versions-typescript/app1/package.json
  react-16-17-18-ssr/remote1/package.json
Labels: workflow-failure

#3262 chore(deps): update dependency magic-string to v0.30.5
  vite-react-simple/vite-react/package.json
  yarn.lock
Labels: workflow-failure

#3261 chore(deps): update dependency lint-staged to v13.3.0
  .github/workflows/on-pull-request.yml
  basic-host-remote/app1/package.json
  basic-host-remote/app1/yarn.lock
  basic-host-remote/app2/package.json
  basic-host-remote/app2/yarn.lock
  bi-directional/app1/package.json
  bi-directional/app1/yarn.lock
  bi-directional/app2/package.json
  bi-directional/app2/yarn.lock
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  modernjs/yarn.lock
  yarn.lock
Labels: workflow-failure

#3224 chore(deps): update dependency @rushstack/eslint-patch to v1.5.1
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/host/yarn.lock
  vite-vue-microfrontends/remote/package.json
  vite-vue-microfrontends/remote/yarn.lock
Labels: e2e-success, workflow-success

#3227 chore(deps): update dependency @sveltejs/vite-plugin-svelte to v2.4.6
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/host/yarn.lock
  vite-svelte-microfrontends/remote/package.json
  vite-svelte-microfrontends/remote/yarn.lock
Labels: e2e-success, workflow-success

#3253 chore(deps): update dependency eslint-plugin-jsx-a11y to v6.7.1
  medusa-nx-native-federation-example/package.json
  yarn.lock
Labels: workflow-cancelled

#3251 chore(deps): update dependency eslint-plugin-cypress to v2.15.1
  medusa-nx-native-federation-example/package.json
  yarn.lock
Labels: workflow-cancelled

#3258 chore(deps): update dependency jsonc-eslint-parser to v2.4.0
  medusa-nx-native-federation-example/package.json
  yarn.lock
Labels: workflow-failure

#3285 fix: correct remote name
  nested/app2/src/ButtonContainer.js
Labels: workflow-failure

#3252 chore(deps): update dependency eslint-plugin-import to v2.29.0
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
  yarn.lock
Labels: workflow-success

#3250 chore(deps): update dependency eslint-config-prettier to v8.10.0
  medusa-nx-native-federation-example/package.json
  yarn.lock
Labels: workflow-success

#3215 chore(deps): update dependency @modern-js/eslint-config to v2.39.0
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  bi-directional/yarn.lock
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs-medusa/yarn.lock
  modernjs/host/package.json
  modernjs/provider/package.json
  yarn.lock
Labels: e2e-failure, workflow-failure

#3186 chore(deps): update dependency @softarc/native-federation-esbuild to v1.1.2
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/host/yarn.lock
  vite-svelte-microfrontends/remote/package.json
  vite-svelte-microfrontends/remote/yarn.lock
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/host/yarn.lock
  vite-vue-microfrontends/remote/package.json
  vite-vue-microfrontends/remote/yarn.lock
Labels: e2e-success, workflow-success

#3200 chore(deps): update dependency autoprefixer to v10.4.16
  i18next-nextjs-react/react-host/package.json
  i18next-nextjs-react/react-remote/package.json
  yarn.lock
Labels: workflow-failure

#3216 chore(deps): update dependency @modern-js/tsconfig to v2.39.0
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  bi-directional/yarn.lock
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs-medusa/yarn.lock
  modernjs/host/package.json
  modernjs/provider/package.json
  yarn.lock
Labels: e2e-failure, workflow-failure

#3213 chore(deps): update dependency @modern-js-app/eslint-config to v2.39.0
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  yarn.lock
Labels: e2e-failure, workflow-failure

#3211 chore(deps): update dependency @emotion/react to v11.11.1
  medusa-example/dsl/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  yarn.lock
Labels: workflow-success

#3254 chore(deps): update dependency eslint-plugin-react to v7.33.2
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  yarn.lock
Labels: workflow-success
