Repository module-federation/module-federation-examples, pull requests merged in 2023-03, with the labels that each got.

#2792 fix: fix cleanup workflow
  .github/workflows/on-pull-request-closed.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-schedule.yml
  .github/workflows/on-workflow-run.yml
Labels: workflow-success

#2794 feat: add setup node to ci & fix: angular samples run & upd: on push workflow
  .github/workflows/on-pull-request.yml
  .github/workflows/on-push.yml
Labels: workflow-success

#2795 refactor: reworked e2e tests for react-nested-routers sample
  cypress/fixtures/constants.ts
  react-nested-routers/e2e/checkReactNestedRoutersApps.cy.ts
  react-nested-routers/e2e/commonChecks.cy.ts
  react-nested-routers/e2e/runAll.cy.ts
  react-nested-routers/e2e/shellAppChecks.cy.ts
Labels: workflow-cancelled

#2803 add e2e for different-react-version-typescript sample
  different-react-versions-typescript/app1/src/components/App.tsx
  different-react-versions-typescript/e2e/checkDiferentReactVersionsTypescriptApp.cy.ts
  different-react-versions-typescript/e2e/methods/methods.ts
Labels: workflow-success

#2781 fix(umd-federation): fix get value demo
  umd-federation/README.md
  umd-federation/app1/src/App.js
  umd-federation/app2/src/index.jsx
Labels: e2e-success, workflow-success

#2798 upd: schedule workflow
  .github/workflows/on-schedule.yml
Labels: workflow-success

#2817 chore: remove streamed federation example
  .gitignore
  README.md
  react-nextjs/.gitignore
  streamed-federation/LICENSE
  streamed-federation/app1/.babelrc
  streamed-federation/app1/.gitignore
  streamed-federation/app1/LICENSE
  streamed-federation/app1/federated-modules.js
  streamed-federation/app1/package.json
  streamed-federation/app1/scripts/get-deps.js
  streamed-federation/app1/serverless.yml
  streamed-federation/app1/src/App.css
  streamed-federation/app1/src/api.js
  streamed-federation/app1/src/client.js
  streamed-federation/app1/src/components/About.js
  streamed-federation/app1/src/components/Contact.js
  streamed-federation/app1/src/components/Header.js
  streamed-federation/app1/src/components/Home.js
  streamed-federation/app1/src/components/Layout.js
  streamed-federation/app1/src/components/Secret.js
  streamed-federation/app1/src/routes.js
  streamed-federation/app1/src/server.js
  streamed-federation/app1/src/store.js
  streamed-federation/app1/webpack.client.config.js
  streamed-federation/app1/webpack.config.js
  streamed-federation/cypress.env.json
  streamed-federation/federated-middleware/LICENSE
  streamed-federation/federated-middleware/package.json
  streamed-federation/federated-middleware/src/extra-route.js
  streamed-federation/federated-middleware/src/noop.js
  streamed-federation/federated-middleware/webpack.config.js
  streamed-federation/package.json
Labels: workflow-success

#2823 fix : typo in host (cra-react-app-rewired)
  cra-react-app-rewired/host/config-overrides.js
Labels: workflow-success

#2816 Add e2e test for react 18 code splitting sample
  cypress/common/selectors.ts
  cypress/fixtures/constants.ts
  different-react-versions-typescript/app1/package.json
  different-react-versions-typescript/app2/package.json
  different-react-versions-typescript/cypress.env.json
  different-react-versions-typescript/package.json
  package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-code-splitting/app2/src/client/components/Content.tsx
  react-18-code-splitting/cypress.env.json
  react-18-code-splitting/e2e/checkReact18CodeSplittingApp.cy.ts
  react-18-code-splitting/package.json
Labels: e2e-success, workflow-success

#2871 chore(deps): pin dependencies (master)
  nextjs-ssr-react-query/package.json
  yarn.lock
Labels: workflow-cancelled

#2866 chore(deps): pin dependencies (master)
  angular11-microfrontends-ngxs/package.json
  angular11-microfrontends-ngxs/yarn.lock
  angular14-react/angular-profile/package.json
  angular15-microfrontends-lazy-components/projects/mdmf-shared/package.json
  yarn.lock
Labels: e2e-success, workflow-success

#2893 chore(deps): update dependency @vitejs/plugin-vue-jsx to v3.0.1
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
  yarn.lock
Labels: e2e-success, workflow-success

#2889 chore(deps): update dependency @sveltejs/vite-plugin-svelte to v2.0.3
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
  yarn.lock
Labels: e2e-success, workflow-success

#2891 chore(deps): update dependency @types/react-dom to v16.9.18
  different-react-versions-16-17-typescript/app1/package.json
  different-react-versions-16-17-typescript/yarn.lock
  different-react-versions-16-18-typescript/app1/package.json
  different-react-versions-16-18-typescript/yarn.lock
  different-react-versions-typescript/app1/package.json
  different-react-versions-typescript/yarn.lock
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/yarn.lock
Labels: e2e-success, workflow-success

#2888 chore(deps): update dependency @softarc/native-federation-esbuild to v1.1.1
  vite-react-microfrontends/host/package-lock.json
  vite-react-microfrontends/host/package.json
  vite-react-microfrontends/remote/package-lock.json
  vite-react-microfrontends/remote/package.json
  vite-svelte-microfrontends/host/package-lock.json
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package-lock.json
  vite-svelte-microfrontends/remote/package.json
  vite-vue-microfrontends/host/package-lock.json
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package-lock.json
  vite-vue-microfrontends/remote/package.json
  yarn.lock
Labels: e2e-success, workflow-success

#2900 Add e2e test for Loadable react 18 sample
  cypress/common/selectors.ts
  cypress/fixtures/constants.ts
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  loadable-react-18/app2/src/client/components/Content.tsx
  loadable-react-18/cypress.env.json
  loadable-react-18/e2e/checkLoadableReact18Apps.cy.ts
  loadable-react-18/package.json
  package.json
  vite-react-simple/e2e/tests/commonChecks.cy.ts
  vite-react-simple/vite-react/src/App.tsx
Labels: e2e-success, workflow-success

#2902 Fix medusa example
  medusa-example/dsl/package.json
  medusa-example/dsl/webpack.config.js
  medusa-example/home/package.json
  medusa-example/home/webpack.config.js
  medusa-example/nav/package.json
  medusa-example/nav/webpack.config.js
  medusa-example/search/package.json
  medusa-example/search/webpack.config.js
  medusa-example/utils/package.json
  medusa-example/utils/webpack.config.js
  medusa-example/yarn.lock
  package.json
  yarn.lock
Labels: workflow-success

#2890 chore(deps): update dependency @types/react to v17.0.55
  different-react-versions-16-17-typescript/app2/package.json
  different-react-versions-16-17-typescript/yarn.lock
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/yarn.lock
  vite-react-simple/vite-react/package.json
  vite-react-simple/vite-react/yarn.lock
Labels: e2e-success, workflow-success

#2911 chore(deps): update dependency json5 to v2.2.3
  native-federation-react/package.json
  yarn.lock
Labels: workflow-failure

#2908 chore(deps): update dependency @sveltejs/vite-plugin-svelte to v2.0.4
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
Labels: e2e-success, workflow-success
