Repository module-federation/module-federation-examples, pull requests merged in 2023-04, with the labels that each got.

#2919 fix: replace all Adaper occurrences with Adapter
  different-react-versions-16-17-typescript/app2/src/components/ModernReactComponent.tsx
  different-react-versions-16-17-typescript/app2/src/components/ReactAdapterProvider.tsx
  different-react-versions-16-17/app2/src/components/ModernReactComponent.js
  different-react-versions-16-17/app2/src/components/ReactAdapterProvider.js
  different-react-versions-16-18-typescript/app2/src/components/ModernReactComponent.tsx
  different-react-versions-16-18-typescript/app2/src/components/ReactAdapterProvider.tsx
  different-react-versions-16-18/app2/src/components/ModernReactComponent.js
  different-react-versions-16-18/app2/src/components/ReactAdapterProvider.js
  different-react-versions-typescript/README.md
  different-react-versions-typescript/app2/src/components/ModernReactComponent.tsx
  different-react-versions-typescript/app2/src/components/ReactAdapterProvider.tsx
  different-react-versions/README.md
  different-react-versions/app2/src/components/ModernReactComponent.js
  different-react-versions/app2/src/components/ReactAdapterProvider.js
Labels: e2e-success, workflow-success

#2923 chore(deps): update dependency @swc/core to v1.3.46
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2924 chore(deps): update dependency @types/jest to v28.1.8
  medusa-nx-native-federation-example/package-lock.json
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2922 chore(deps): update dependency @swc/cli to v0.1.62
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2930 chore(deps): update dependency ts-jest to v28.0.8
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2936 fix(deps): update dependency node-fetch to v2.6.9
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
Labels: workflow-success

#2935 chore(deps): update nginx docker tag to v1.23.4
  advanced-api/dynamic-remotes-runtime-environment-variables/host/Dockerfile
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/Dockerfile
Labels: e2e-success, workflow-success

#2934 chore(deps): update jest monorepo to v28.1.3
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2932 chore(deps): update dependency prettier to v2.8.7
  medusa-nx-native-federation-example/package.json
Labels: workflow-success

#2927 chore(deps): update dependency esm-node-services to v0.7.13
  native-federation-react/package.json
Labels: workflow-failure

#2938 feat: native federation plugins example
  native-federation-tests-typescript-plugins/README.md
  native-federation-tests-typescript-plugins/host/.gitignore
  native-federation-tests-typescript-plugins/host/babel.config.js
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/host/public/index.html
  native-federation-tests-typescript-plugins/host/rspack.config.js
  native-federation-tests-typescript-plugins/host/src/bootstrap.tsx
  native-federation-tests-typescript-plugins/host/src/component/Component.test.tsx
  native-federation-tests-typescript-plugins/host/src/component/Component.tsx
  native-federation-tests-typescript-plugins/host/src/component/__snapshots__/Component.test.tsx.snap
  native-federation-tests-typescript-plugins/host/src/index.ts
  native-federation-tests-typescript-plugins/host/tsconfig.json
  native-federation-tests-typescript-plugins/host/vite.config.js
  native-federation-tests-typescript-plugins/host/webpack.config.js
  native-federation-tests-typescript-plugins/package.json
  native-federation-tests-typescript-plugins/remote/.gitignore
  native-federation-tests-typescript-plugins/remote/babel.config.js
  native-federation-tests-typescript-plugins/remote/package.json
  native-federation-tests-typescript-plugins/remote/rspack.config.js
  native-federation-tests-typescript-plugins/remote/src/components/anotherButton/AnotherButton.tsx
  native-federation-tests-typescript-plugins/remote/src/components/anotherButton/index.ts
  native-federation-tests-typescript-plugins/remote/src/components/button/Button.tsx
  native-federation-tests-typescript-plugins/remote/src/components/button/Inner/Inner.tsx
  native-federation-tests-typescript-plugins/remote/src/components/button/index.ts
  native-federation-tests-typescript-plugins/remote/src/index.ts
  native-federation-tests-typescript-plugins/remote/tsconfig.json
  native-federation-tests-typescript-plugins/remote/vite.config.ts
  native-federation-tests-typescript-plugins/remote/webpack.config.js
  native-federation-tests-typescript-plugins/yarn.lock
  package.json
  yarn.lock
Labels: workflow-success

#2920 add samples to ci
  cypress/fixtures/constants.ts
  package.json
Labels: e2e-success, workflow-success

#2921 feat: dynamic remotes on node
  README.md
  dynamic-remotes-node/README.md
  dynamic-remotes-node/app1/index.js
  dynamic-remotes-node/app1/noop.js
  dynamic-remotes-node/app1/webpack.config.js
  dynamic-remotes-node/app2/expose-sample.js
  dynamic-remotes-node/app2/index.js
  dynamic-remotes-node/app2/webpack.config.js
  dynamic-remotes-node/package.json
Labels: workflow-success

#2960 fix: Include config in Vite example to use environment variables from…
  vite-react-microfrontends/remote/src/App.tsx
  vite-react-microfrontends/remote/src/enviroment.ts
  vite-react-microfrontends/remote/vite.config.ts
  vite-svelte-microfrontends/remote/src/App.svelte
  vite-svelte-microfrontends/remote/src/enviroment.ts
  vite-svelte-microfrontends/remote/vite.config.ts
  vite-vue-microfrontends/remote/src/App.vue
  vite-vue-microfrontends/remote/src/enviroment.ts
  vite-vue-microfrontends/remote/vite.config.ts
Labels: workflow-failure

#2948 fix: medusa-nx-native-federation-example on win platform
  medusa-nx-native-federation-example/packages/native-federation-plugin/src/lib/index.ts
Labels: workflow-success

#2982 fix: medusa-nx-native-federation-example on linux platform
  medusa-nx-native-federation-example/package-lock.json
  medusa-nx-native-federation-example/package.json
  medusa-nx-native-federation-example/packages/native-federation-plugin/src/executors/build/remotes.ts
  medusa-nx-native-federation-example/packages/native-federation-plugin/src/executors/dashboard/dashboard.ts
Labels: workflow-success

#2953 Add Azure Functions Node v4 Example
  cloud/azure-functions-node-v4/.gitignore
  cloud/azure-functions-node-v4/.vscode/extensions.json
  cloud/azure-functions-node-v4/.vscode/launch.json
  cloud/azure-functions-node-v4/.vscode/settings.json
  cloud/azure-functions-node-v4/.vscode/tasks.json
  cloud/azure-functions-node-v4/README.md
  cloud/azure-functions-node-v4/package-lock.json
  cloud/azure-functions-node-v4/package.json
  cloud/azure-functions-node-v4/remote/config/module-federation.js
  cloud/azure-functions-node-v4/remote/config/webpack.client.js
  cloud/azure-functions-node-v4/remote/config/webpack.server.js
  cloud/azure-functions-node-v4/remote/config/webpack.shared.js
  cloud/azure-functions-node-v4/remote/package-lock.json
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/remote/public/index.html
  cloud/azure-functions-node-v4/remote/src/bootstrap.tsx
  cloud/azure-functions-node-v4/remote/src/components/Consumer.tsx
  cloud/azure-functions-node-v4/remote/src/components/Widget.tsx
  cloud/azure-functions-node-v4/remote/src/index.ts
  cloud/azure-functions-node-v4/remote/tsconfig.json
  cloud/azure-functions-node-v4/remote/webpack.config.js
  cloud/azure-functions-node-v4/shell/api/.funcignore
  cloud/azure-functions-node-v4/shell/api/.gitignore
  cloud/azure-functions-node-v4/shell/api/host.json
  cloud/azure-functions-node-v4/shell/api/package-lock.json
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/api/src/client.tsx
  cloud/azure-functions-node-v4/shell/api/src/fake.ts
  cloud/azure-functions-node-v4/shell/api/src/index.tsx
  cloud/azure-functions-node-v4/shell/api/tsconfig.json
  cloud/azure-functions-node-v4/shell/api/webpack.config.js
  cloud/azure-functions-node-v4/shell/client/package-lock.json
  cloud/azure-functions-node-v4/shell/client/package.json
  cloud/azure-functions-node-v4/shell/client/src/bootstrap.tsx
  cloud/azure-functions-node-v4/shell/client/src/components/App.tsx
  cloud/azure-functions-node-v4/shell/client/src/components/Main.tsx
  cloud/azure-functions-node-v4/shell/client/src/components/Provider.tsx
  cloud/azure-functions-node-v4/shell/client/src/components/Router.tsx
  cloud/azure-functions-node-v4/shell/client/src/index.ts
  cloud/azure-functions-node-v4/shell/client/tsconfig.json
  cloud/azure-functions-node-v4/shell/client/webpack.config.js
  cloud/azure-functions-node-v4/tsconfig.base.json
Labels: workflow-failure
