Repository module-federation/module-federation-examples, pull requests merged in 2023-11, with the labels that each got.

#3219 chore(deps): update dependency @originjs/vite-plugin-federation to v1.3.2
  vue3-demo-federation-with-vite/vite-side/package.json
Labels: e2e-success, workflow-success

#3222 chore(deps): update dependency @rspack/cli to v0.3.8
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
Labels: workflow-success

#3292 chore(deps): update jest monorepo
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  nextjs-ssr-react-query/package.json
  yarn.lock
Labels: workflow-success

#3290 chore(deps): update dependency @types/react-helmet to v6.1.8
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app2/package.json
  yarn.lock
Labels: e2e-success, workflow-success

#3208 fix(quasar-cli-vue3): fixed prod builds
  quasar-cli-vue3-webpack-javascript/README.md
  quasar-cli-vue3-webpack-javascript/app-exposes/.quasar/artifacts.json
  quasar-cli-vue3-webpack-javascript/app-exposes/.quasar/client-entry.js
  quasar-cli-vue3-webpack-javascript/app-exposes/README.md
  quasar-cli-vue3-webpack-javascript/app-exposes/envs/env.dev.json
  quasar-cli-vue3-webpack-javascript/app-exposes/envs/env.json
  quasar-cli-vue3-webpack-javascript/app-exposes/envs/env.prod.json
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/apple-icon-120x120.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/apple-icon-152x152.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/apple-icon-167x167.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/apple-icon-180x180.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/icon-128x128.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/icon-192x192.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/icon-256x256.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/icon-384x384.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/icon-512x512.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/ms-icon-144x144.png
  quasar-cli-vue3-webpack-javascript/app-exposes/public/icons/safari-pinned-tab.svg
  quasar-cli-vue3-webpack-javascript/app-exposes/quasar.config.js
  quasar-cli-vue3-webpack-javascript/app-exposes/src-pwa/custom-service-worker.js
  quasar-cli-vue3-webpack-javascript/app-exposes/src-pwa/pwa-flag.d.ts
  quasar-cli-vue3-webpack-javascript/app-exposes/src-pwa/register-service-worker.js
  quasar-cli-vue3-webpack-javascript/app-general/.quasar/artifacts.json
  quasar-cli-vue3-webpack-javascript/app-general/.quasar/client-entry.js
  quasar-cli-vue3-webpack-javascript/app-general/README.md
  quasar-cli-vue3-webpack-javascript/app-general/envs/env.dev.json
  quasar-cli-vue3-webpack-javascript/app-general/envs/env.json
  quasar-cli-vue3-webpack-javascript/app-general/envs/env.prod.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/apple-icon-120x120.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/apple-icon-152x152.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/apple-icon-167x167.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/apple-icon-180x180.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/icon-128x128.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/icon-192x192.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/icon-256x256.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/icon-384x384.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/icon-512x512.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/ms-icon-144x144.png
  quasar-cli-vue3-webpack-javascript/app-general/public/icons/safari-pinned-tab.svg
  quasar-cli-vue3-webpack-javascript/app-general/quasar.config.js
Labels: workflow-failure

#3291 chore(deps): update dependency @types/react-is to v18.2.3
  nextjs-ssr-react-query/package.json
  yarn.lock
Labels: workflow-success

#3198 chore(deps): update dependency @types/serialize-javascript to v5.0.4
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  yarn.lock
Labels: workflow-success

#3300 move timeout location to step not job
  .github/workflows/on-pull-request.yml
Labels: workflow-success

#3202 chore(deps): update dependency tailwindcss to v3.3.5
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css/expose-remotes/expose-tailwind-css-global/package.json
  federated-css/expose-remotes/expose-tailwind-css-module/package.json
  yarn.lock
Labels: workflow-failure

#3302 chore(config): migrate renovate config
  renovate.json
Labels: workflow-success

#3218 chore(deps): update dependency @module-federation/native-federation-typescript to v0.2.6
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  yarn.lock
Labels: workflow-success

#3248 chore(deps): update dependency esbuild to v0.19.5
  medusa-nx-native-federation-example/package.json
  native-federation-react/package.json
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
  yarn.lock
Labels: workflow-failure

#3239 chore(deps): update dependency css-loader to v6.8.1
  angular14-react/react-user-list/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  css-isolation/app1/package.json
  css-isolation/app2/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  react-in-vue/layout/package.json
  react-nextjs/react-host-remote/remote/package.json
  rollup-federation-demo/rs-sidecar/package.json
  shared-store-cross-framework/vue-counter/package.json
  vite-react-simple/rs-sidecart/package.json
  vue2-in-vue3/vue2/package.json
  vue2-in-vue3/vue3/package.json
  vue3-demo-federation-with-vite/webpack-side/package.json
  vue3-demo/home/package.json
  vue3-demo/layout/package.json
  yarn.lock
Labels: workflow-failure

#3260 chore(deps): update dependency less to v4.2.0
  federated-css-react-ssr/expose-apps/expose-less/package.json
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
Labels: workflow-success

#3236 chore(deps): update dependency axios to v1.6.1
  loadable-react-16/app1/package.json
  styled-components/app1/package.json
  yarn.lock
Labels: workflow-cancelled

#3225 chore(deps): update dependency @shelex/cypress-allure-plugin to v2.40.0
  package.json
  yarn.lock
Labels: workflow-success

#3214 chore(deps): update dependency @modern-js/app-tools to v2.39.2
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  yarn.lock
Labels: workflow-cancelled

#3293 chore(deps): update react monorepo
  angular14-react/angular-profile/package.json
  angular14-react/react-user-list/package.json
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  different-react-versions-16-17-typescript/app1/package.json
  different-react-versions-16-17-typescript/app2/package.json
  different-react-versions-16-18-typescript/app1/package.json
  different-react-versions-16-18-typescript/app2/package.json
  different-react-versions-typescript/app1/package.json
  different-react-versions-typescript/app2/package.json
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  medusa-nx-native-federation-example/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  native-federation-react/package.json
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  nextjs-ssr-react-query/package.json
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
  typescript-monorepo/app1/package.json
  typescript-monorepo/app2/package.json
  typescript-project-references/app1/package.json
  typescript-project-references/app2/package.json
  typescript-react-fallback/app1/package.json
  typescript-react-fallback/app2/package.json
  typescript-react-monorepo-test/packages/host/package.json
  typescript-react-monorepo-test/packages/remote/package.json
  typescript-react-monorepo/packages/app1/package.json
  typescript-react-monorepo/packages/app2/package.json
  typescript-react-monorepo/packages/host/package.json
  typescript/app1/package.json
  typescript/app2/package.json
  vite-react-simple/vite-react/package.json
  yarn.lock
Labels: workflow-failure

#3217 chore(deps): update dependency @module-federation/native-federation-tests to v0.2.0
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  yarn.lock
Labels: workflow-success

#3229 chore(deps): update dependency @types/jasmine to v4.6.2
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  angular11-microfrontends-scully/package.json
  angular12-microfrontends/package.json
  angular14-react/angular-profile/package.json
  angular15-microfrontends-lazy-components/package.json
  angular15-vue3/package.json
  yarn.lock
Labels: workflow-failure

#3199 chore(deps): update dependency @vitejs/plugin-vue-jsx to v3.0.2
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
  yarn.lock
Labels: workflow-failure

#3197 chore(deps): update dependency @types/react-test-renderer to v18.0.6
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  yarn.lock
Labels: workflow-success

#3332 Remove CI legacy yarn references
  .github/workflows/on-pull-request.yml
Labels: workflow-success

#3205 fix(deps): update dependency antd to v4.24.14
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
Labels: workflow-success

#3183 chore(deps): update dependency @module-federation/vite to v0.2.8
  pnpm-lock.yaml
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
Labels: workflow-success

#3264 chore(deps): update dependency ng-packagr to v15.2.2
  angular15-microfrontends-lazy-components/package.json
  angular15-vue3/package.json
Labels: workflow-failure

#3256 chore(deps): update dependency esm-node-services to v0.9.1
  native-federation-react/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#3430 fix: modernjs public pathing
  modernjs/host/modern.config.ts
  modernjs/provider/modern.config.ts
Labels: workflow-success
