Repository module-federation/module-federation-examples, pull requests merged in 2024-01, with the labels that each got.

#3486 Migrate from CRA to RsBuild
  cra/README.md
  cra/cypress.env.json
  cra/e2e/checkCraApps.cy.ts
  cra/host/package.json
  cra/host/rsbuild.config.ts
  cra/package.json
  cra/remote/package.json
  cra/remote/public/index.html
  cra/remote/rsbuild.config.ts
  pnpm-lock.yaml
Labels: workflow-success

#3492 rsbuild migration for vue, rspack migration for angular-react
  README.md
  angular14-react/pnpm-lock.yaml
  angular14-react/react-user-list/package.json
  angular14-react/react-user-list/rspack.config.js
  angular15-vue3/vue-remote/package.json
  angular15-vue3/vue-remote/rsbuild.config.js
  angular15-vue3/vue-remote/src/router/index.js
  angular15-vue3/vue-remote/vue.config.js
  pnpm-lock.yaml
Labels: workflow-failure

#3497 Legacy cmds
  .github/workflows/on-pull-request.yml
  advanced-api/automatic-vendor-sharing/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/host/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/host/public/index.html
  advanced-api/dynamic-remotes-runtime-environment-variables/host/rspack.config.js
  advanced-api/dynamic-remotes-runtime-environment-variables/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/public/index.html
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/rspack.config.js
  advanced-api/dynamic-remotes/app1/package.json
  advanced-api/dynamic-remotes/app1/webpack.config.js
  advanced-api/dynamic-remotes/app2/package.json
  advanced-api/dynamic-remotes/app2/webpack.config.js
  advanced-api/dynamic-remotes/app3/package.json
  advanced-api/dynamic-remotes/app3/webpack.config.js
  advanced-api/dynamic-remotes/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3502 Add dynamic vendor sharing functionality to runtime plugins
  cypress-e2e/fixtures/constants.ts
  pnpm-lock.yaml
  runtime-plugins/README.md
  runtime-plugins/control-sharing/README.md
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app1/public/index.html
  runtime-plugins/control-sharing/app1/rspack.config.js
  runtime-plugins/control-sharing/app1/src/App.js
  runtime-plugins/control-sharing/app1/src/Button.js
  runtime-plugins/control-sharing/app1/src/ControlPanel/index.js
  runtime-plugins/control-sharing/app1/src/bootstrap.js
  runtime-plugins/control-sharing/app1/src/index.js
  runtime-plugins/control-sharing/app1/webpack.config.js
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/control-sharing/app2/public/index.html
  runtime-plugins/control-sharing/app2/rspack.config.js
  runtime-plugins/control-sharing/app2/src/App.js
  runtime-plugins/control-sharing/app2/src/Button.js
  runtime-plugins/control-sharing/app2/src/bootstrap.js
  runtime-plugins/control-sharing/app2/src/index.js
  runtime-plugins/control-sharing/app2/webpack.config.js
  runtime-plugins/control-sharing/control-share.js
  runtime-plugins/control-sharing/control-share.ts
  runtime-plugins/control-sharing/cypress.env.json
  runtime-plugins/control-sharing/e2e/checkAutomaticVendorApps.cy.ts
  runtime-plugins/control-sharing/package.json
Labels: workflow-success

#3440 feat: use @module-federation/runtime
  basic-host-remote/package.json
  bi-directional/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app1/src/App.js
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#3521 rspack cdn example update
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app1/rspack.config.js
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/app2/rspack.config.js
  federated-library-from-cdn/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  federated-library-from-cdn/remoteLibrary/rspack.dev.js
  federated-library-from-cdn/remoteLibrary/rspack.prod.js
  output.md
  pnpm-lock.yaml
  updateReadmeExampleList.js
Labels: workflow-success

#3528 fix commands of comprehensive demo
  comprehensive-demo-react16/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3538 Comprehensive demo fix
  comprehensive-demo-react16/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3543 Update modernjs
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#3544 upgrade rspack
  advanced-api/dynamic-remotes/app1/package.json
  advanced-api/dynamic-remotes/app2/package.json
  advanced-api/dynamic-remotes/app3/package.json
  angular15-vue3/vue-remote/package.json
  cra/host/package.json
  cra/remote/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#3548 Upgrade rsbuild
  angular15-vue3/vue-remote/package.json
  cra/host/package.json
  cra/remote/package.json
  pnpm-lock.yaml
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app1/src/ControlPanel/index.js
  runtime-plugins/control-sharing/app2/package.json
Labels: workflow-failure

#3549 feat: API Controlled Remotes
  comprehensive-demo-react18/app-04/public/225.css
  comprehensive-demo-react18/app-04/public/966.css
  cypress-e2e/fixtures/constants.ts
  pnpm-lock.yaml
  runtime-plugins/README.md
  runtime-plugins/control-sharing/app1/rspack.config.js
  runtime-plugins/control-sharing/app1/src/App.js
  runtime-plugins/control-sharing/app1/src/ControlPanel/index.js
  runtime-plugins/control-sharing/app1/webpack.config.js
  runtime-plugins/control-sharing/app2/rspack.config.js
  runtime-plugins/control-sharing/app2/src/App.js
  runtime-plugins/control-sharing/app2/src/Button.js
  runtime-plugins/control-sharing/app2/webpack.config.js
  runtime-plugins/control-sharing/control-share.js
  runtime-plugins/control-sharing/control-share.ts
  runtime-plugins/remote-control/README.md
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app1/pick-remote.js
  runtime-plugins/remote-control/app1/pick-remote.ts
  runtime-plugins/remote-control/app1/rspack.config.js
  runtime-plugins/remote-control/app1/src/App.js
  runtime-plugins/remote-control/app1/webpack.config.js
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app2/rspack.config.js
  runtime-plugins/remote-control/app2/src/App.js
  runtime-plugins/remote-control/app2/src/Button.js
  runtime-plugins/remote-control/app2/webpack.config.js
  runtime-plugins/remote-control/app3/package.json
  runtime-plugins/remote-control/app3/rspack.config.js
  runtime-plugins/remote-control/app3/src/App.js
  runtime-plugins/remote-control/app3/src/Button.js
  runtime-plugins/remote-control/app3/webpack.config.js
  runtime-plugins/remote-control/e2e/checkAutomaticVendorApps.cy.ts
  runtime-plugins/remote-control/package.json
  runtime-plugins/remote-control/pick-remote.js
  runtime-plugins/remote-control/pick-remote.ts
Labels: workflow-cancelled

#3585 Update dependencies to use enhanced ModuleFederationPlugin
  advanced-api/automatic-vendor-sharing/app1/package.json
  advanced-api/automatic-vendor-sharing/app1/webpack.config.js
  advanced-api/automatic-vendor-sharing/app2/package.json
  advanced-api/automatic-vendor-sharing/app2/webpack.config.js
  advanced-api/dynamic-remotes-runtime-environment-variables/host/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/host/webpack.config.js
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/webpack.config.js
  advanced-api/dynamic-remotes-synchronous-imports/app1/ExternalTemplateRemotesPlugin.js
  advanced-api/dynamic-remotes-synchronous-imports/app1/package.json
  advanced-api/dynamic-remotes-synchronous-imports/app1/runtimePlugin.js
  advanced-api/dynamic-remotes-synchronous-imports/app1/webpack.config.js
  advanced-api/dynamic-remotes-synchronous-imports/app2/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#3606 chore: use rspack+modernjs
  modernjs/host/modern.config.ts
  modernjs/package.json
  modernjs/provider/modern.config.ts
  pnpm-lock.yaml
Labels: workflow-cancelled

#3613 feat: remote ingress runtime plugin
  pnpm-lock.yaml
  pnpm-workspace.yaml
  runtime-plugins/remote-router/README.md
  runtime-plugins/remote-router/host/.babelrc
  runtime-plugins/remote-router/host/.gitignore
  runtime-plugins/remote-router/host/.nvmrc
  runtime-plugins/remote-router/host/config/runtimePlugin.js
  runtime-plugins/remote-router/host/config/webpack.config.build.js
  runtime-plugins/remote-router/host/config/webpack.config.default.js
  runtime-plugins/remote-router/host/config/webpack.config.modulefederation.js
  runtime-plugins/remote-router/host/config/webpack.config.resolve.js
  runtime-plugins/remote-router/host/config/webpack.config.serve.js
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/host/postcss.config.js
  runtime-plugins/remote-router/host/src/bootstrap.js
  runtime-plugins/remote-router/host/src/features/Home/Home.jsx
  runtime-plugins/remote-router/host/src/features/Home/index.tsx
  runtime-plugins/remote-router/host/src/index.html
  runtime-plugins/remote-router/host/src/index.js
  runtime-plugins/remote-router/host/webpack.config.js
  runtime-plugins/remote-router/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-workspace.yaml
  runtime-plugins/remote-router/remotes-monorepo/.editorconfig
  runtime-plugins/remote-router/remotes-monorepo/.eslintignore
  runtime-plugins/remote-router/remotes-monorepo/.eslintrc.json
  runtime-plugins/remote-router/remotes-monorepo/.gitignore
  runtime-plugins/remote-router/remotes-monorepo/.nvmrc
  runtime-plugins/remote-router/remotes-monorepo/.prettierignore
  runtime-plugins/remote-router/remotes-monorepo/README.md
  runtime-plugins/remote-router/remotes-monorepo/jest.config.ts
  runtime-plugins/remote-router/remotes-monorepo/jest.preset.js
  runtime-plugins/remote-router/remotes-monorepo/nx.json
  runtime-plugins/remote-router/remotes-monorepo/package.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/.babelrc
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/.eslintrc.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/jest.config.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/module-federation.config.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/project.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/src/HelloWorld/HelloWorld.tsx
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/src/HelloWorld/index.tsx
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/tsconfig.app.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/tsconfig.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/tsconfig.spec.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/webpack.config.prod.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-one/webpack.config.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/.babelrc
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/.eslintrc.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/jest.config.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/module-federation.config.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/project.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/src/Button/Button.tsx
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/src/Button/index.tsx
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/tsconfig.app.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/tsconfig.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/tsconfig.spec.json
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/webpack.config.prod.ts
  runtime-plugins/remote-router/remotes-monorepo/packages/remote-two/webpack.config.ts
  runtime-plugins/remote-router/remotes-monorepo/tsconfig.base.json
Labels: workflow-success

#3620 Runtime Plugins - Annotate Import Files
  pnpm-lock.yaml
  runtime-plugins/remote-router/package.json
Labels: workflow-success
