Repository module-federation/module-federation-examples, pull requests merged in 2024-04, with the labels that each got.

#3762 feat(runtime-plugins): add isolated shared dependencies plugin example
  runtime-plugins/isolate-shared-dependencies/.gitignore
  runtime-plugins/isolate-shared-dependencies/README.md
  runtime-plugins/isolate-shared-dependencies/app1/isolatePlugin.ts
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app1/src/App.vue
  runtime-plugins/isolate-shared-dependencies/app1/src/bootstrap.ts
  runtime-plugins/isolate-shared-dependencies/app1/src/index.ts
  runtime-plugins/isolate-shared-dependencies/app1/src/shims.d.ts
  runtime-plugins/isolate-shared-dependencies/app1/tsconfig.json
  runtime-plugins/isolate-shared-dependencies/app1/webpack.config.js
  runtime-plugins/isolate-shared-dependencies/app2/isolatePlugin.ts
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app2/src/App.vue
  runtime-plugins/isolate-shared-dependencies/app2/src/bootstrap.ts
  runtime-plugins/isolate-shared-dependencies/app2/src/index.ts
  runtime-plugins/isolate-shared-dependencies/app2/src/shims.d.ts
  runtime-plugins/isolate-shared-dependencies/app2/tsconfig.json
  runtime-plugins/isolate-shared-dependencies/app2/webpack.config.js
  runtime-plugins/isolate-shared-dependencies/app3/isolatePlugin.ts
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/app3/src/App.vue
  runtime-plugins/isolate-shared-dependencies/app3/src/bootstrap.ts
  runtime-plugins/isolate-shared-dependencies/app3/src/index.ts
  runtime-plugins/isolate-shared-dependencies/app3/src/shims.d.ts
  runtime-plugins/isolate-shared-dependencies/app3/tsconfig.json
  runtime-plugins/isolate-shared-dependencies/app3/webpack.config.js
  runtime-plugins/isolate-shared-dependencies/package-lock.json
  runtime-plugins/isolate-shared-dependencies/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/isolatePluginFactory.ts
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/isolate-shared-dependencies/shared-lib-2/index.d.ts
  runtime-plugins/isolate-shared-dependencies/shared-lib-2/index.js
  runtime-plugins/isolate-shared-dependencies/shared-lib-2/package.json
  runtime-plugins/isolate-shared-dependencies/shared-lib/index.d.ts
  runtime-plugins/isolate-shared-dependencies/shared-lib/index.js
  runtime-plugins/isolate-shared-dependencies/shared-lib/package.json
  runtime-plugins/isolate-shared-dependencies/tsconfig.json
Labels: workflow-failure

#3805 updated dashboard user name
  dashboard-admin-react-rspack-material-ui/sidebar/src/pages/sidebar/MyProSidebar.jsx
Labels: workflow-failure

#3807 docs: Direct the user to a new document
  README.md
Labels: workflow-success

#3810 update next mf
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  nextjs-dynamic-ssr/checkout/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  nextjs-ssr/checkout/package.json
  nextjs-ssr/home/package.json
  nextjs-ssr/pnpm-lock.yaml
  nextjs-ssr/shop/package.json
  nextjs-v12/checkout/package.json
  nextjs-v12/home/package.json
  nextjs-v12/shop/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  nextjs-v14/checkout/package.json
  nextjs-v14/home/package.json
  nextjs-v14/shop/package.json
  pnpm-lock.yaml
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-success

#3814 Apollo rspack federation
  apollo-client/app1/config/module-federation.js
  apollo-client/app1/config/rspack.client.js
  apollo-client/app1/config/rspack.server.js
  apollo-client/app1/config/webpack.client.js
  apollo-client/app1/config/webpack.server.js
  apollo-client/app1/package.json
  apollo-client/app2/config/module-federation.js
  apollo-client/app2/config/rspack.client.js
  apollo-client/app2/config/rspack.server.js
  apollo-client/app2/config/webpack.client.js
  apollo-client/app2/config/webpack.server.js
  apollo-client/app2/package.json
  apollo-client/cypress.env.json
  apollo-client/e2e/checkCraApps.cy.ts
  apollo-client/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3812 hmr example with runtime and buildtime remotes
  rspack_hmr/README.md
  rspack_hmr/app2/.gitignore
  rspack_hmr/app2/index.html
  rspack_hmr/app2/package.json
  rspack_hmr/app2/pnpm-lock.yaml
  rspack_hmr/app2/rspack.config.js
  rspack_hmr/app2/src/App.css
  rspack_hmr/app2/src/App.tsx
  rspack_hmr/app2/src/Hello.tsx
  rspack_hmr/app2/src/assets/react.svg
  rspack_hmr/app2/src/bootstrap.tsx
  rspack_hmr/app2/src/index.css
  rspack_hmr/app2/src/index.tsx
  rspack_hmr/app2/src/pi.ts
  rspack_hmr/app2/src/react-env.d.ts
  rspack_hmr/app2/tsconfig.json
  rspack_hmr/host/.gitignore
  rspack_hmr/host/@mf-types/app_02/Hello.d.ts
  rspack_hmr/host/@mf-types/app_02/apis.d.ts
  rspack_hmr/host/@mf-types/app_02/compiled-types/Hello.d.ts
  rspack_hmr/host/@mf-types/index.d.ts
  rspack_hmr/host/index.html
  rspack_hmr/host/package.json
  rspack_hmr/host/pnpm-lock.yaml
  rspack_hmr/host/rspack.config.js
  rspack_hmr/host/src/App.css
  rspack_hmr/host/src/App.tsx
  rspack_hmr/host/src/bootstrap.tsx
  rspack_hmr/host/src/index.css
  rspack_hmr/host/src/index.tsx
  rspack_hmr/host/src/react-env.d.ts
  rspack_hmr/host/tsconfig.json
  rspack_hmr/runhost/.gitignore
  rspack_hmr/runhost/index.html
  rspack_hmr/runhost/package.json
  rspack_hmr/runhost/pnpm-lock.yaml
  rspack_hmr/runhost/rspack.config.js
  rspack_hmr/runhost/src/App.css
  rspack_hmr/runhost/src/App.tsx
  rspack_hmr/runhost/src/bootstrap.tsx
  rspack_hmr/runhost/src/index.css
  rspack_hmr/runhost/src/index.tsx
  rspack_hmr/runhost/src/react-env.d.ts
  rspack_hmr/runhost/tsconfig.json
Labels: workflow-failure

#3823 Hmr sample
  pnpm-lock.yaml
  rspack_hmr/README.md
  rspack_hmr/app2/.gitignore
  rspack_hmr/app2/index.html
  rspack_hmr/app2/package.json
  rspack_hmr/app2/rspack.config.js
  rspack_hmr/app2/src/App.css
  rspack_hmr/app2/src/App.tsx
  rspack_hmr/app2/src/Hello.tsx
  rspack_hmr/app2/src/assets/react.svg
  rspack_hmr/app2/src/bootstrap.tsx
  rspack_hmr/app2/src/index.css
  rspack_hmr/app2/src/index.tsx
  rspack_hmr/app2/src/pi.ts
  rspack_hmr/app2/src/react-env.d.ts
  rspack_hmr/app2/tsconfig.json
  rspack_hmr/host/.gitignore
  rspack_hmr/host/@mf-types/app_02/Hello.d.ts
  rspack_hmr/host/@mf-types/app_02/apis.d.ts
  rspack_hmr/host/@mf-types/app_02/compiled-types/Hello.d.ts
  rspack_hmr/host/@mf-types/app_02/compiled-types/pi.d.ts
  rspack_hmr/host/@mf-types/app_02/pi.d.ts
  rspack_hmr/host/@mf-types/index.d.ts
  rspack_hmr/host/index.html
  rspack_hmr/host/package.json
  rspack_hmr/host/rspack.config.js
  rspack_hmr/host/src/App.css
  rspack_hmr/host/src/App.tsx
  rspack_hmr/host/src/bootstrap.tsx
  rspack_hmr/host/src/index.css
  rspack_hmr/host/src/index.tsx
  rspack_hmr/host/src/react-env.d.ts
  rspack_hmr/host/tsconfig.json
  rspack_hmr/package.json
  rspack_hmr/runhost/.gitignore
  rspack_hmr/runhost/index.html
  rspack_hmr/runhost/package.json
  rspack_hmr/runhost/rspack.config.js
  rspack_hmr/runhost/src/App.css
  rspack_hmr/runhost/src/App.tsx
  rspack_hmr/runhost/src/bootstrap.tsx
  rspack_hmr/runhost/src/index.css
  rspack_hmr/runhost/src/index.tsx
  rspack_hmr/runhost/src/react-env.d.ts
  rspack_hmr/runhost/tsconfig.json
Labels: workflow-cancelled

#3825 chore: add example
  pnpm-workspace.yaml
  react-manifest-example/README.md
  react-manifest-example/host/@mf-types/index.d.ts
  react-manifest-example/host/@mf-types/remote1/apis.d.ts
  react-manifest-example/host/@mf-types/remote1/app.d.ts
  react-manifest-example/host/@mf-types/remote1/button.d.ts
  react-manifest-example/host/@mf-types/remote1/compiled-types/app.d.ts
  react-manifest-example/host/@mf-types/remote1/compiled-types/button.d.ts
  react-manifest-example/host/@mf-types/remote2/apis.d.ts
  react-manifest-example/host/@mf-types/remote2/button.d.ts
  react-manifest-example/host/@mf-types/remote2/compiled-types/button.d.ts
  react-manifest-example/host/README.md
  react-manifest-example/host/package.json
  react-manifest-example/host/rsbuild.config.ts
  react-manifest-example/host/src/App.css
  react-manifest-example/host/src/App.tsx
  react-manifest-example/host/src/bootstrap.tsx
  react-manifest-example/host/src/env.d.ts
  react-manifest-example/host/src/index.tsx
  react-manifest-example/host/src/navigation.tsx
  react-manifest-example/host/src/pages/Home.tsx
  react-manifest-example/host/src/pages/remote1.tsx
  react-manifest-example/host/src/pages/remote2.tsx
  react-manifest-example/host/tsconfig.json
  react-manifest-example/package.json
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/pnpm-workspace.yaml
  react-manifest-example/remote1/README.md
  react-manifest-example/remote1/package.json
  react-manifest-example/remote1/rsbuild.config.ts
  react-manifest-example/remote1/src/App.css
  react-manifest-example/remote1/src/App.tsx
  react-manifest-example/remote1/src/bootstrap.tsx
  react-manifest-example/remote1/src/button.tsx
  react-manifest-example/remote1/src/env.d.ts
  react-manifest-example/remote1/src/index.tsx
  react-manifest-example/remote1/tsconfig.json
  react-manifest-example/remote2/README.md
  react-manifest-example/remote2/package.json
  react-manifest-example/remote2/rsbuild.config.ts
  react-manifest-example/remote2/src/App.css
  react-manifest-example/remote2/src/App.tsx
  react-manifest-example/remote2/src/bootstrap.tsx
  react-manifest-example/remote2/src/button.tsx
  react-manifest-example/remote2/src/env.d.ts
  react-manifest-example/remote2/src/index.tsx
  react-manifest-example/remote2/tsconfig.json
Labels: workflow-failure

#3829 chore(deps): update dependency @headlessui/react to v1.7.19
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3835 Fix next13
  nextjs-v13/e2e/checkNextJSv12Apps.cy.ts
  nextjs-v13/package.json
  nextjs-v13/shared/index.js
  nextjs-v13/shop/pages/_app.js
Labels: workflow-success

#3834 chore(deps): update dependency @ngxs/devtools-plugin to v3.8.2
  angular11-microfrontends-ngxs/package.json
  angular14-react/angular-profile/package.json
  angular14-react/pnpm-lock.yaml
  pnpm-lock.yaml
Labels: workflow-failure
