Repository module-federation/module-federation-examples, pull requests merged in 2024-06, with the labels that each got.

#3992 chore(deps): update dependency @rsdoctor/webpack-plugin to v0.2.5
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3993 chore(deps): update dependency @pmmmwh/react-refresh-webpack-plugin to v0.5.15
  comprehensive-demo-react18/app-01/package.json
  comprehensive-demo-react18/app-03/package.json
  comprehensive-demo-react18/app-04/package.json
  comprehensive-demo-react18/app-05/package.json
  pnpm-lock.yaml
  react-livereload/remote1/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#3991 chore(deps): update dependency @rsdoctor/rspack-plugin to v0.3.0
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3996 chore(deps): update dependency @rsdoctor/rspack-plugin to v0.3.1
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4000 chore: general housekeeping
  advanced-api/dynamic-remotes-runtime-environment-variables/host/src/components/Main.js
  advanced-api/dynamic-remotes/app1/src/App.js
  advanced-api/dynamic-remotes/package.json
  cypress-e2e/fixtures/constants.ts
Labels: workflow-success

#4002 chore: general housekeeping
  angular14-react/pnpm-lock.yaml
  apollo-client/package.json
  cra-react-app-rewired/pnpm-lock.yaml
  cra/host/package.json
  cra/host/rsbuild.config.ts
  cra/host/scripts/build.js
  cra/host/scripts/overrides/webpack-config.js
  cra/host/scripts/start.js
  cra/package.json
  cra/remote/package.json
  cra/remote/rsbuild.config.ts
  cra/remote/scripts/build.js
  cra/remote/scripts/overrides/webpack-config.js
  cra/remote/scripts/start.js
  css-isolation/app1/rspack.config.js
  css-isolation/app2/rspack.config.js
  federated-npm/app1/webpack.config.js
  federated-npm/app3/webpack.config.js
  federated-npm/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-ssr/pnpm-lock.yaml
  pnpm-lock.yaml
  remix/pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  umd-federation/pnpm-lock.yaml
Labels: workflow-cancelled

#3994 chore(deps): update dependency @swc/core to v1.5.24
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4006 chore(deps): pin dependencies
  apollo-client/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3999 chore(deps): update dependency ts-jest to v29.1.4
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  typescript-react-monorepo-test/packages/host/package.json
Labels: workflow-success

#3998 chore(deps): update dependency sass to v1.77.4
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-success

#3989 chore(deps): update dependency @module-federation/node to v2.2.9
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  dynamic-remotes-node/package.json
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-jss/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/package.json
  server-side-rendering/remote1/package.json
  server-side-rendering/remote2/package.json
  server-side-rendering/shell/package.json
  simple-node/node-host/package.json
  simple-node/node-local-remote/package.json
  simple-node/node-remote/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
Labels: workflow-failure

#4012 chore(deps): update dependency @rsdoctor/rspack-plugin to v0.3.2
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4011 chore(deps): update dependency @types/node to v16.18.98
  medusa-nx-native-federation-example/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4013 chore(deps): update dependency @types/node to v18.19.34
  angular-universal-ssr/client-app/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  native-federation-react/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
Labels: workflow-failure

#3990 chore(deps): update dependency @module-federation/runtime to v0.1.18
  advanced-api/dynamic-remotes/app1/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react18/app-01/package.json
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  federated-npm/app1/package.json
  federated-npm/app2/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-v12/shared/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/offline-remote/app1/package.json
  runtime-plugins/offline-remote/app2/package.json
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app3/package.json
Labels: workflow-success

#4010 chore(deps): update swc monorepo
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4014 chore(deps): update dependency svelte-loader to v3.2.3
  comprehensive-demo-react16/app-04/package.json
  comprehensive-demo-react18/app-04/package.json
  pnpm-lock.yaml
  rspack-webpack-interop/app-04/package.json
Labels: workflow-success

#3952 chore: general housekeeping
  bi-directional/app1/modern.config.js
  bi-directional/app1/package.json
  bi-directional/app1/src/routes/page.jsx
  bi-directional/app2/modern.config.js
  bi-directional/app2/package.json
  cra-react-app-rewired/pnpm-lock.yaml
  cypress-e2e/fixtures/constants.ts
  cypress-e2e/package.json
  dynamic-remotes-node/app1/index.js
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/rspack.config.js
  dynamic-system-host/app1/src/App.js
  dynamic-system-host/app2/rspack.config.js
  dynamic-system-host/app3/rspack.config.js
  dynamic-system-host/package.json
  nextjs-ssr/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
  remix/pnpm-lock.yaml
  rspack-remix/app1/webpack.browser.js
  rspack-webpack-interop/package.json
  runtime-plugins/control-sharing/app2/webpack.config.js
  runtime-plugins/remote-router/pnpm-lock.yaml
  umd-federation/package.json
Labels: workflow-failure

#4017 fix(deps): update dependency express to v4.19.2 [security]
  pnpm-lock.yaml
Labels: workflow-success

#4020 chore(deps): pin dependency kill-port to 2.0.1
  dynamic-remotes-node/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4019 chore(deps): update dependency esbuild to v0.21.5
  medusa-nx-native-federation-example/package.json
  native-federation-react/package.json
  pnpm-lock.yaml
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
Labels: workflow-success

#4018 chore(deps): update dependency @vitejs/plugin-react to v4.3.1
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  pnpm-lock.yaml
  vite-react-microfrontends/host/package.json
  vite-react-microfrontends/remote/package.json
Labels: workflow-success

#4015 chore(deps): update dependency tailwindcss to v3.4.4
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css/expose-remotes/expose-tailwind-css-global/package.json
  federated-css/expose-remotes/expose-tailwind-css-module/package.json
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  pnpm-lock.yaml
Labels: workflow-success

#3836 debug alternative remote devtools
  angular14-react/pnpm-lock.yaml
  pnpm-lock.yaml
  pnpm-workspace.yaml
  react-manifest-example/host/@mf-types/remote1/compiled-types/app.d.ts
  react-manifest-example/host/@mf-types/remote1/compiled-types/button.d.ts
  react-manifest-example/host/@mf-types/remote2/compiled-types/button.d.ts
  react-manifest-example/package.json
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/pnpm-workspace.yaml
  react-manifest-example/remote2_alternative/README.md
  react-manifest-example/remote2_alternative/package.json
  react-manifest-example/remote2_alternative/rsbuild.config.ts
  react-manifest-example/remote2_alternative/src/App.css
  react-manifest-example/remote2_alternative/src/App.tsx
  react-manifest-example/remote2_alternative/src/bootstrap.tsx
  react-manifest-example/remote2_alternative/src/button.tsx
  react-manifest-example/remote2_alternative/src/env.d.ts
  react-manifest-example/remote2_alternative/src/index.tsx
  react-manifest-example/remote2_alternative/tsconfig.json
  remix/pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  umd-federation/pnpm-lock.yaml
Labels: workflow-failure

#4025 chore(deps): update dependency @module-federation/node to v2.2.10
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  dynamic-remotes-node/package.json
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-jss/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/package.json
  server-side-rendering/remote1/package.json
  server-side-rendering/remote2/package.json
  server-side-rendering/shell/package.json
  simple-node/node-host/package.json
  simple-node/node-local-remote/package.json
  simple-node/node-remote/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
Labels: workflow-success

#4023 fix(deps): update dependency express to v4.19.2 [security]
  pnpm-lock.yaml
Labels: workflow-success

#4031 chore(deps): update dependency @swc/core to v1.6.1
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4036 chore(deps): update dependency sass to v1.77.6
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-success

#4035 chore(deps): update dependency eslint-config-next to v14.2.4
  i18next-nextjs-react/next-host/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4016 chore(deps): update dependency tslib to v2.6.3
  cloud/azure-functions-node-v4/shell/api/package.json
  pnpm-lock.yaml
  vite-svelte-microfrontends/host/package.json
  vite-svelte-microfrontends/remote/package.json
Labels: workflow-success

#4040 chore(deps): update dependency @heroicons/react to v2.1.4
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4039 fix(deps): update dependency next to v14 [security]
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4034 chore(deps): update dependency @testing-library/jest-dom to v6.4.6
  cra-react-app-rewired/host/package.json
  cra-react-app-rewired/pnpm-lock.yaml
  cra-react-app-rewired/remote/package.json
Labels: workflow-failure

#4026 chore(deps): update dependency @module-federation/runtime to v0.1.20
  advanced-api/dynamic-remotes/app1/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react18/app-01/package.json
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  federated-npm/app1/package.json
  federated-npm/app2/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-v12/shared/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/offline-remote/app1/package.json
  runtime-plugins/offline-remote/app2/package.json
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app3/package.json
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-failure

#4027 chore(deps): update babel monorepo to v7.24.7
  pnpm-lock.yaml
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-success

#4045 chore(deps): update dependency ts-jest to v29.1.5
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  typescript-react-monorepo-test/packages/host/package.json
Labels: workflow-success

#4042 chore(deps): update dependency @module-federation/node to v2.2.11
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  dynamic-remotes-node/package.json
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-jss/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/package.json
  server-side-rendering/remote1/package.json
  server-side-rendering/remote2/package.json
  server-side-rendering/shell/package.json
  simple-node/node-host/package.json
  simple-node/node-local-remote/package.json
  simple-node/node-remote/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
Labels: workflow-success

#4024 chore(deps): pin dependencies
  pnpm-lock.yaml
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/remote2_alternative/package.json
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-success

#4044 chore(deps): update dependency @types/node to v18.19.37
  angular-universal-ssr/client-app/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  native-federation-react/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
Labels: workflow-failure

#4043 chore(deps): update dependency @types/node to v16.18.100
  medusa-nx-native-federation-example/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4055 chore(deps): update dependency eslint-plugin-react to v7.34.3
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4053 chore(deps): update dependency @rsdoctor/rspack-plugin to v0.3.4
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4054 chore(deps): update dependency @swc/core to v1.6.3
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4062 chore(deps): update dependency @types/node to v16.18.101
  medusa-nx-native-federation-example/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4058 chore(deps): update dependency webpack-virtual-modules to v0.6.2
  pnpm-lock.yaml
  react-storybook/host/package.json
Labels: workflow-success

#4061 fix(deps): update material-ui monorepo
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4066 chore(deps): update dependency @modern-js/eslint-config to v2.54.0
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4063 chore(deps): update dependency @types/node to v18.19.38
  angular-universal-ssr/client-app/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  native-federation-react/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  vite-vue-microfrontends/host/package.json
  vite-vue-microfrontends/remote/package.json
Labels: workflow-failure

#4068 chore(deps): update dependency @modern-js/tsconfig to v2.54.1
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4059 chore(deps): pin dependencies
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4060 chore(deps): update vue monorepo to v3.4.29
  pnpm-lock.yaml
  shared-store-cross-framework/shell/package.json
  shared-store-cross-framework/vue-counter/package.json
  vite-vue-microfrontends/host/package.json
  vue2-in-vue3/vue2/package.json
  vue2-in-vue3/vue3/package.json
  vue3-demo-federation-with-vite/vite-side/package.json
  vue3-demo-federation-with-vite/webpack-side/package.json
  vue3-demo/home/package.json
  vue3-demo/layout/package.json
Labels: workflow-failure

#4065 chore(deps): update dependency @modern-js/app-tools to v2.54.1
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4064 chore(deps): update dependency @modern-js-app/eslint-config to v2.54.1
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4078 fix(deps): update nivo monorepo to v0.87.0
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4090 chore(deps): update dependency @types/node to v18.19.39
  angular-universal-ssr/client-app/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  native-federation-react/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4089 chore(deps): pin dependency wait-on to 7.2.0
  pnpm-lock.yaml
  shared-routing/package.json
Labels: workflow-success

#4075 chore(deps): update nginx docker tag to v1.27.0
  advanced-api/dynamic-remotes-runtime-environment-variables/host/Dockerfile
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/Dockerfile
Labels: workflow-success

#4071 chore(deps): update dependency cypress to v13.12.0
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  package.json
  pnpm-lock.yaml
  typescript-react-monorepo-test/packages/host/package.json
Labels: workflow-success

#4092 chore(deps): update vue monorepo to v3.4.30
  pnpm-lock.yaml
  shared-store-cross-framework/shell/package.json
  shared-store-cross-framework/vue-counter/package.json
  vue2-in-vue3/vue2/package.json
  vue2-in-vue3/vue3/package.json
  vue3-demo/home/package.json
  vue3-demo/layout/package.json
Labels: workflow-success

#4079 fix(deps): update react-router monorepo to v6.23.1
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
  react-nextjs/react-host-remote/host/package.json
  react-nextjs/react-host-remote/remote/package.json
  shared-routing/dashboard/package.json
  shared-routing/profile/package.json
  shared-routing/sales/package.json
  shared-routing/shell/package.json
Labels: workflow-success

#4088 chore(deps): update dependency vite to v5.3.1
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4073 chore(deps): update dependency eslint-plugin-jsx-a11y to v6.9.0
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4074 chore(deps): update dependency lint-staged to v13.3.0
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4072 chore(deps): update dependency cypress-real-events to v1.13.0
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4102 chore(deps): update dependency concurrently to v8.2.2
  angular-universal-ssr/package.json
  clo/package.json
  cloud/azure-functions-node-v4/package.json
  cra/package.json
  federated-library-from-cdn/package.json
  genesis/package.json
  medusa-delegate-example/package.json
  medusa-example/package.json
  modernjs/package.json
  native-federation-react/package.json
  nextjs-v12/package.json
  nextjs-v13/package.json
  nextjs-v14/package.json
  package.json
  pnpm-lock.yaml
  react-livereload/package.json
  react-nextjs/nextjs-host-react-remote/package.json
  react-nextjs/nextjs-host-react-remote/remote/package.json
  react-nextjs/nextjs-host-remote/package.json
  react-nextjs/react-host-nextjs-remote/host/package.json
  react-nextjs/react-host-nextjs-remote/package.json
  react-nextjs/react-host-remote/host/package.json
  react-nextjs/react-host-remote/package.json
  react-nextjs/react-host-remote/remote/package.json
  react-storybook/package.json
  redux-reducer-injection/package.json
  server-side-render-only/package.json
  server-side-rendering/package.json
  simple-node/package.json
  typescript-react-monorepo-test/package.json
  typescript-react-monorepo/package.json
Labels: workflow-failure

#4100 chore(deps): update dependency babel-plugin-styled-components to v2.1.4
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4097 chore(deps): update dependency @vue/eslint-config-typescript to v13
  pnpm-lock.yaml
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-success

#4101 chore(deps): update dependency browser-sync to v3
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-failure

#4098 chore(deps): update dependency @webpack-cli/serve to v2
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-delegate-example/utils/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  medusa-example/utils/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4095 chore(deps): update dependency @types/jasmine to v5
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4077 fix(deps): update dependency next to v14.2.4
  nextjs-ssr-react-query/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4096 chore(deps): update dependency @vue/eslint-config-airbnb to v8
  pnpm-lock.yaml
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-success

#4076 fix(deps): update dependency @modern-js/runtime to v2.54.1
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4069 chore(deps): update dependency @rsdoctor/webpack-plugin to v0.3.4
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4070 chore(deps): update dependency @types/jest to v29.5.12
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4091 chore(deps): update swc monorepo
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4103 chore(deps): update dependency copy-webpack-plugin to v12
  advanced-api/dynamic-remotes-runtime-environment-variables/host/package.json
  advanced-api/dynamic-remotes-runtime-environment-variables/remote/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  rust-wasm/remote/package.json
Labels: workflow-success

#4106 chore(deps): update dependency css-minimizer-webpack-plugin to v7
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-failure

#4116 chore(deps): update dependency find-up to v7
  pnpm-lock.yaml
  shared-routing/dashboard/package.json
  shared-routing/profile/package.json
  shared-routing/sales/package.json
  shared-routing/shell/package.json
Labels: workflow-success

#4115 chore(deps): update dependency eslint-webpack-plugin to v4
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
Labels: workflow-success

#4112 chore(deps): update dependency eslint-plugin-cypress to v3
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4110 chore(deps): update dependency eslint-config-next to v14
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-success

#4114 chore(deps): update dependency eslint-plugin-vuejs-accessibility to v2
  pnpm-lock.yaml
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-success

#4111 chore(deps): update dependency eslint-config-prettier to v9
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
Labels: workflow-success

#4107 chore(deps): update dependency cypress-wait-until to v3
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4083 chore(deps): update dependency @nguniversal/builders to v16
  angular-universal-ssr/host-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4121 chore(deps): update dependency lerna to v8
  package.json
  pnpm-lock.yaml
  rust-wasm/package.json
  shared-context/package.json
  styled-components/package.json
Labels: workflow-failure

#4117 chore(deps): update dependency husky to v9
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4123 chore(deps): update dependency lint-staged to v15.2.7
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4122 chore(deps): update dependency less-loader to v12
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css/expose-remotes/expose-less/package.json
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4119 chore(deps): update dependency jasmine-spec-reporter to v7
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4113 chore(deps): update dependency eslint-plugin-vue to v9.26.0
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  vue-cli/consumer/package.json
  vue-cli/core/package.json
  vue-cli/other/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-failure

#4120 chore(deps): update dependency karma-jasmine to v5
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4108 chore(deps): update dependency esbuild-loader to v4.2.0
  medusa-delegate-example/home/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  medusa-example/utils/package.json
  pnpm-lock.yaml
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  rust-wasm/host/package.json
Labels: workflow-failure

#4126 chore(deps): update react monorepo
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
Labels: workflow-success

#4118 chore(deps): update dependency jasmine-core to v5
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4127 chore(deps): update dependency ngx-build-plus to v18
  angular11-microfrontends-ngrx/package.json
  angular11-microfrontends-ngxs/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4109 chore(deps): update dependency eslint to v9
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  medusa-nx-native-federation-example/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  vue-cli/consumer/package.json
  vue-cli/core/package.json
  vue-cli/other/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-failure

#4131 chore(deps): update dependency postcss-loader to v8
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css/expose-remotes/expose-tailwind-css-global/package.json
  federated-css/expose-remotes/expose-tailwind-css-module/package.json
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  i18next-nextjs-react/react-host/package.json
  i18next-nextjs-react/react-remote/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-success

#4129 chore(deps): update dependency nodemon to v3
  pnpm-lock.yaml
  server-side-render-only/package.json
Labels: workflow-success

#3904 chore(deps): update dependency @remix-run/dev to v2.9.2
  pnpm-lock.yaml
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
Labels: workflow-success

#4133 chore(deps): update dependency pretty-quick to v4
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4136 chore(deps): update dependency sass-loader to v14
  angular-universal-ssr/client-app/package.json
  angular-universal-ssr/host-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css/expose-remotes/expose-scss/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-success

#4132 chore(deps): update dependency prettier to v3.3.2
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  medusa-nx-native-federation-example/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  nextjs-ssr-react-query/package.json
  package.json
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-failure

#4135 chore(deps): update dependency rimraf to v5.0.7
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  cloud/azure-functions-node-v4/remote/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  rust-wasm/remote/package.json
  server-side-rendering/shell/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
Labels: workflow-failure

#4140 chore(deps): update dependency ts-loader to v9.5.1
  comprehensive-demo-react18/app-05/package.json
  pnpm-lock.yaml
  rspack-webpack-interop/app-05/package.json
  typescript-react-monorepo-test/packages/host/package.json
  typescript-react-monorepo-test/packages/remote/package.json
  typescript-react-monorepo/packages/host/package.json
Labels: workflow-success

#4141 chore(deps): update dependency @modern-js-app/eslint-config to v2.54.2
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4138 chore(deps): update dependency style-loader to v4
  cloud/azure-functions-node-v4/shell/api/package.json
  complete-react-case/component-app/package.json
  comprehensive-demo-react16/app-04/package.json
  comprehensive-demo-react18/app-04/package.json
  css-isolation/app1/package.json
  css-isolation/app2/package.json
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  federated-css/expose-remotes/expose-css-module/package.json
  federated-css/expose-remotes/expose-css/package.json
  federated-css/expose-remotes/expose-less/package.json
  federated-css/expose-remotes/expose-scss/package.json
  federated-css/expose-remotes/expose-tailwind-css-global/package.json
  federated-css/expose-remotes/expose-tailwind-css-module/package.json
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  i18next-nextjs-react/react-host/package.json
  i18next-nextjs-react/react-remote/package.json
  medusa-delegate-example/dsl/package.json
  medusa-delegate-example/home/package.json
  medusa-delegate-example/nav/package.json
  medusa-delegate-example/search/package.json
  medusa-example/dsl/package.json
  medusa-example/home/package.json
  medusa-example/nav/package.json
  medusa-example/search/package.json
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  pnpm-lock.yaml
  react-nextjs/react-host-remote/remote/package.json
  rspack-webpack-interop/app-04/package.json
  rspack-webpack-offload/component-app/package.json
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
Labels: workflow-failure

#4143 Submit rsbuild vue 3 vuex tailwindcss postcss example
  README.md
  rsbuild-vue3-vuex/README.md
  rsbuild-vue3-vuex/consumer/.gitignore
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/consumer/postcss.config.js
  rsbuild-vue3-vuex/consumer/rsbuild.config.ts
  rsbuild-vue3-vuex/consumer/src/App.vue
  rsbuild-vue3-vuex/consumer/src/bootstrap.js
  rsbuild-vue3-vuex/consumer/src/main.js
  rsbuild-vue3-vuex/consumer/src/router/index.js
  rsbuild-vue3-vuex/consumer/src/router/routes.js
  rsbuild-vue3-vuex/consumer/src/store/index.js
  rsbuild-vue3-vuex/consumer/src/views/Index.vue
  rsbuild-vue3-vuex/consumer/tailwind.config.js
  rsbuild-vue3-vuex/consumer/yarn.lock
  rsbuild-vue3-vuex/provider/.gitignore
  rsbuild-vue3-vuex/provider/package.json
  rsbuild-vue3-vuex/provider/postcss.config.cjs
  rsbuild-vue3-vuex/provider/rsbuild.config.ts
  rsbuild-vue3-vuex/provider/src/App.vue
  rsbuild-vue3-vuex/provider/src/bootstrap.js
  rsbuild-vue3-vuex/provider/src/main.js
  rsbuild-vue3-vuex/provider/src/store/index.js
  rsbuild-vue3-vuex/provider/src/views/AppIndex.vue
  rsbuild-vue3-vuex/provider/src/views/Landing.vue
  rsbuild-vue3-vuex/provider/src/yarn.lock
  rsbuild-vue3-vuex/provider/tailwind.config.js
  rsbuild-vue3-vuex/provider/yarn.lock
Labels: workflow-failure

#4139 chore(deps): update dependency svelte to v4
  comprehensive-demo-react16/app-04/package.json
  comprehensive-demo-react18/app-04/package.json
  pnpm-lock.yaml
  rspack-webpack-interop/app-04/package.json
Labels: workflow-success

#4145 chore(deps): pin dependencies
  pnpm-lock.yaml
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-success

#4144 chore(deps): update dependency @modern-js/app-tools to v2.54.2
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4150 chore(deps): update dependency @rsbuild/plugin-vue to v0.7.9
  pnpm-lock.yaml
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-success

#4149 chore(deps): update dependency @rsbuild/core to v0.7.9
  pnpm-lock.yaml
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-success

#4146 chore(deps): update dependency @modern-js/eslint-config to v2.54.2
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4155 fix(deps): update dependency @module-federation/nextjs-mf to v8.3.24
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  nextjs-dynamic-ssr/checkout/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  nextjs-ssr/checkout/package.json
  nextjs-ssr/home/package.json
  nextjs-ssr/pnpm-lock.yaml
  nextjs-ssr/shop/package.json
  nextjs-v12/checkout/package.json
  nextjs-v12/home/package.json
  nextjs-v12/shop/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  nextjs-v14/checkout/package.json
  nextjs-v14/home/package.json
  nextjs-v14/shop/package.json
  pnpm-lock.yaml
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-failure

#4154 fix(deps): update dependency @modern-js/runtime to v2.54.2
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4151 chore(deps): update dependency lerna to v8.1.5
  package.json
  pnpm-lock.yaml
  rust-wasm/package.json
  shared-context/package.json
  styled-components/package.json
Labels: workflow-success

#4153 chore(deps): update dependency ts-node to v10.9.2
  angular-universal-ssr/client-app/package.json
  angular-universal-ssr/host-app/package.json
  medusa-nx-native-federation-example/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4158 fix(deps): update dependency @module-federation/sdk to v0.2.1
  comprehensive-demo-react18/app-01/package.json
  nextjs-dynamic-ssr/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
Labels: workflow-failure

#4052 chore(deps): update dependency @module-federation/runtime to v0.2.1
  advanced-api/dynamic-remotes/app1/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react18/app-01/package.json
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  federated-npm/app1/package.json
  federated-npm/app2/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-v12/shared/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/offline-remote/app1/package.json
  runtime-plugins/offline-remote/app2/package.json
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app3/package.json
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-failure

#4148 chore(deps): update dependency @module-federation/node to v2.2.14
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  dynamic-remotes-node/package.json
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-jss/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/package.json
  server-side-rendering/remote1/package.json
  server-side-rendering/remote2/package.json
  server-side-rendering/shell/package.json
  simple-node/node-host/package.json
  simple-node/node-local-remote/package.json
  simple-node/node-remote/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
Labels: workflow-failure

#4157 chore(deps): update dependency mocha to v10.5.1
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4159 fix(deps): update dependency vue to v3.4.30
  pnpm-lock.yaml
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-failure

#4161 chore(deps): update dependency tsconfig-paths-webpack-plugin to v4.1.0
  cloud/azure-functions-node-v4/remote/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  pnpm-lock.yaml
  typescript-project-references/app1/package.json
  typescript-project-references/app2/package.json
  typescript-react-fallback/app1/package.json
  typescript-react-fallback/app2/package.json
Labels: workflow-success

#4160 fix(deps): update react-router monorepo to v6.24.0
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
  react-nextjs/react-host-remote/host/package.json
  react-nextjs/react-host-remote/remote/package.json
  shared-routing/dashboard/package.json
  shared-routing/profile/package.json
  shared-routing/sales/package.json
  shared-routing/shell/package.json
Labels: workflow-success

#4168 chore(deps): update dependency @rsbuild/core to v0.7.10
  clo/host/package.json
  clo/remote/package.json
  cra/host/package.json
  cra/remote/package.json
  pnpm-lock.yaml
  react-manifest-example/host/package.json
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/remote1/package.json
  react-manifest-example/remote2/package.json
  react-manifest-example/remote2_alternative/package.json
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-success
