Repository module-federation/module-federation-examples, pull requests merged in 2024-07, with the labels that each got.

#4176 fix(deps): update dependency next to v13 [security]
  i18next-nextjs-react/next-host/package.json
  nextjs-v12/checkout/package.json
  nextjs-v12/home/package.json
  nextjs-v12/shop/package.json
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-failure

#4170 chore(deps): update dependency @rsbuild/plugin-vue to v0.7.10
  pnpm-lock.yaml
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/provider/package.json
Labels: workflow-success

#4169 chore(deps): update dependency @rsbuild/plugin-react to v0.7.10
  clo/host/package.json
  clo/remote/package.json
  cra/host/package.json
  cra/remote/package.json
  pnpm-lock.yaml
  react-manifest-example/host/package.json
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/remote1/package.json
  react-manifest-example/remote2/package.json
  react-manifest-example/remote2_alternative/package.json
Labels: workflow-success

#4167 chore(deps): update dependency @modern-js/tsconfig to v2.54.6
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4166 chore(deps): update dependency @modern-js/eslint-config to v2.54.6
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4165 chore(deps): update dependency @modern-js/app-tools to v2.54.6
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4164 chore(deps): update dependency @modern-js-app/eslint-config to v2.54.6
  basic-host-remote/app1/package.json
  basic-host-remote/app2/package.json
  bi-directional/app1/package.json
  bi-directional/app2/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  pnpm-lock.yaml
Labels: workflow-failure

#4178 chore(deps): pin dependencies
  i18next-nextjs-react/i18next-shared-lib/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4182 chore(deps): update dependency @rsdoctor/webpack-plugin to v0.3.7
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4181 chore(deps): update dependency @rsdoctor/rspack-plugin to v0.3.7
  comprehensive-demo-react18/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4192 fix(deps): update dependency @module-federation/nextjs-mf to v8.3.27
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  nextjs-dynamic-ssr/checkout/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  nextjs-ssr/checkout/package.json
  nextjs-ssr/home/package.json
  nextjs-ssr/pnpm-lock.yaml
  nextjs-ssr/shop/package.json
  nextjs-v12/checkout/package.json
  nextjs-v12/home/package.json
  nextjs-v12/shop/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  nextjs-v14/checkout/package.json
  nextjs-v14/home/package.json
  nextjs-v14/shop/package.json
  pnpm-lock.yaml
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-failure

#4195 fix(deps): update react-router monorepo to v6.24.1
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
  react-nextjs/react-host-remote/host/package.json
  react-nextjs/react-host-remote/remote/package.json
  shared-routing/dashboard/package.json
  shared-routing/profile/package.json
  shared-routing/sales/package.json
  shared-routing/shell/package.json
Labels: workflow-success

#4194 fix(deps): update dependency @mui/x-data-grid to v6.20.3
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4196 chore(deps): update dependency @module-federation/native-federation-tests to v0.6.0
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4190 chore(deps): update vue monorepo to v3.4.31
  pnpm-lock.yaml
  rsbuild-vue3-vuex/consumer/package.json
  rsbuild-vue3-vuex/provider/package.json
  shared-store-cross-framework/shell/package.json
  shared-store-cross-framework/vue-counter/package.json
  vue2-in-vue3/vue2/package.json
  vue2-in-vue3/vue3/package.json
  vue3-demo/home/package.json
  vue3-demo/layout/package.json
Labels: workflow-success

#4193 fix(deps): update dependency @module-federation/sdk to v0.2.4
  comprehensive-demo-react18/app-01/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
Labels: workflow-success

#4180 chore(deps): update dependency @module-federation/runtime to v0.2.4
  advanced-api/dynamic-remotes/app1/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react18/app-01/package.json
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  federated-npm/app1/package.json
  federated-npm/app2/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-v12/shared/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/offline-remote/app1/package.json
  runtime-plugins/offline-remote/app2/package.json
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app3/package.json
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-failure

#4197 chore(deps): update dependency @module-federation/native-federation-typescript to v0.6.0
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4199 chore(deps): update dependency @remix-run/dev to v2.10.2
  pnpm-lock.yaml
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
Labels: workflow-success

#4177 fix(deps): update dependency next to v14.1.1 [security]
  nextjs-dynamic-ssr/pnpm-lock.yaml
Labels: workflow-failure

#4201 chore(deps): update dependency esbuild to v0.23.0
  medusa-nx-native-federation-example/package.json
  native-federation-react/package.json
  pnpm-lock.yaml
  remix/app1/package.json
  remix/app2/package.json
  remix/pnpm-lock.yaml
  rspack-remix/app1/package.json
  rspack-remix/app2/package.json
Labels: workflow-success

#4202 chore(deps): update dependency eslint to v9.6.0
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  medusa-nx-native-federation-example/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  vue-cli/consumer/package.json
  vue-cli/core/package.json
  vue-cli/other/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-failure

#4204 chore(deps): update dependency mocha to v10.6.0
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4203 chore(deps): update dependency eslint-plugin-vue to v9.27.0
  pnpm-lock.yaml
  quasar-cli-vue3-webpack-javascript/app-exposes/package.json
  quasar-cli-vue3-webpack-javascript/app-general/package.json
  vue-cli/consumer/package.json
  vue-cli/core/package.json
  vue-cli/other/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-failure

#4205 chore(deps): update swc monorepo
  cloud/azure-functions-node-v4/shell/api/package.json
  cloud/azure-functions-node-v4/shell/client/package.json
  medusa-nx-native-federation-example/package.json
  pnpm-lock.yaml
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
Labels: workflow-success

#4206 fix(deps): update material-ui monorepo to v5.16.0
  dashboard-admin-react-rspack-material-ui/dashboard-app/package.json
  dashboard-admin-react-rspack-material-ui/faq-app/package.json
  dashboard-admin-react-rspack-material-ui/root/package.json
  dashboard-admin-react-rspack-material-ui/sidebar/package.json
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4207 chore(deps): update dependency postcss-preset-env to v9.5.16
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4208 chore(deps): update dependency @testing-library/cypress to v10
  pnpm-lock.yaml
  typescript-react-monorepo-test/packages/host/package.json
Labels: workflow-success

#4209 chore(deps): update dependency @testing-library/jest-dom to v6
  pnpm-lock.yaml
  typescript-react-monorepo-test/packages/host/package.json
Labels: workflow-success

#4214 fix(deps): update dependency @module-federation/sdk to v0.2.5
  comprehensive-demo-react18/app-01/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
Labels: workflow-success

#4212 chore(deps): update dependency @module-federation/runtime to v0.2.5
  advanced-api/dynamic-remotes/app1/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react18/app-01/package.json
  dynamic-remotes-node/package.json
  dynamic-system-host/app1/package.json
  dynamic-system-host/app2/package.json
  dynamic-system-host/app3/package.json
  federated-npm/app1/package.json
  federated-npm/app2/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-v12/shared/package.json
  pnpm-lock.yaml
  rspack_hmr/app2/package.json
  rspack_hmr/host/package.json
  rspack_hmr/runhost/package.json
  runtime-plugins/control-sharing/app1/package.json
  runtime-plugins/control-sharing/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/isolate-shared-dependencies/plugin/package.json
  runtime-plugins/offline-remote/app1/package.json
  runtime-plugins/offline-remote/app2/package.json
  runtime-plugins/remote-control/app1/package.json
  runtime-plugins/remote-control/app2/package.json
  runtime-plugins/remote-control/app3/package.json
  runtime-plugins/single-runtime/app1/package.json
  runtime-plugins/single-runtime/app2/package.json
Labels: workflow-failure

#4213 fix(deps): update dependency @module-federation/nextjs-mf to v8.3.28
  federated-css/consumers-nextjs/any-combination/package.json
  federated-css/consumers-nextjs/combination-of-4/package.json
  federated-css/consumers-nextjs/jss-and-tailwind-global/package.json
  federated-css/consumers-nextjs/jss-css-and-tailwind-module/package.json
  federated-css/consumers-nextjs/less-and-styled-component/package.json
  i18next-nextjs-react/next-host/package.json
  nextjs-dynamic-ssr/checkout/package.json
  nextjs-dynamic-ssr/home/package.json
  nextjs-dynamic-ssr/pnpm-lock.yaml
  nextjs-dynamic-ssr/shop/package.json
  nextjs-react/host-app/package.json
  nextjs-ssr-react-query/package.json
  nextjs-ssr/checkout/package.json
  nextjs-ssr/home/package.json
  nextjs-ssr/pnpm-lock.yaml
  nextjs-ssr/shop/package.json
  nextjs-v12/checkout/package.json
  nextjs-v12/home/package.json
  nextjs-v12/shop/package.json
  nextjs-v13/checkout/package.json
  nextjs-v13/home/package.json
  nextjs-v13/shop/package.json
  nextjs-v14/checkout/package.json
  nextjs-v14/home/package.json
  nextjs-v14/shop/package.json
  pnpm-lock.yaml
  react-nextjs/nextjs-host-react-remote/host/package.json
  react-nextjs/nextjs-host-remote/host/package.json
  react-nextjs/nextjs-host-remote/remote/package.json
  react-nextjs/react-host-nextjs-remote/remote/package.json
Labels: workflow-failure

#4216 chore(deps): update dependency typescript to v5.5.3
  angular-universal-ssr/client-app/package.json
  angular-universal-ssr/host-app/package.json
  cloud/azure-functions-node-v4/shell/api/package.json
  comprehensive-demo-react16/app-05/package.json
  comprehensive-demo-react18/app-05/package.json
  different-react-versions-16-17-typescript/app1/package.json
  different-react-versions-16-17-typescript/app2/package.json
  different-react-versions-typescript/app1/package.json
  different-react-versions-typescript/app2/package.json
  i18next-nextjs-react/i18next-shared-lib/package.json
  i18next-nextjs-react/next-host/package.json
  i18next-nextjs-react/react-host/package.json
  i18next-nextjs-react/react-remote/package.json
  medusa-nx-native-federation-example/package.json
  modernjs-classic-tractor-example/checkout/package.json
  modernjs-classic-tractor-example/decide/package.json
  modernjs-classic-tractor-example/explore/package.json
  modernjs-medusa/host/package.json
  modernjs-medusa/provider/package.json
  modernjs/host/package.json
  modernjs/provider/package.json
  native-federation-tests-typescript-plugins/host/package.json
  native-federation-tests-typescript-plugins/remote/package.json
  nextjs-ssr-react-query/package.json
  package.json
  pnpm-lock.yaml
  react-manifest-example/host/package.json
  react-manifest-example/pnpm-lock.yaml
  react-manifest-example/remote1/package.json
  react-manifest-example/remote2/package.json
  react-manifest-example/remote2_alternative/package.json
  rsbuild-vue3-vuex/consumer/package.json
  rspack-webpack-interop/app-05/package.json
  runtime-plugins/isolate-shared-dependencies/app1/package.json
  runtime-plugins/isolate-shared-dependencies/app2/package.json
  runtime-plugins/isolate-shared-dependencies/app3/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  runtime-plugins/remote-router/remotes-monorepo/package.json
  typescript-monorepo/app1/package.json
  typescript-monorepo/app2/package.json
  typescript-project-references/app1/package.json
  typescript-project-references/app2/package.json
  typescript-react-fallback/app1/package.json
  typescript-react-fallback/app2/package.json
  typescript-react-monorepo-test/packages/host/package.json
  typescript-react-monorepo-test/packages/remote/package.json
  typescript-react-monorepo/packages/app1/package.json
  typescript-react-monorepo/packages/app2/package.json
  typescript-react-monorepo/packages/host/package.json
  typescript/app1/package.json
  typescript/app2/package.json
  vue3-cli-demo/app-exposes/package.json
  vue3-cli-demo/app-general/package.json
Labels: workflow-cancelled

#4222 chore(deps): update dependency webpack-merge to v6
  apollo-client/app1/package.json
  apollo-client/app2/package.json
  federated-css-react-ssr/expose-apps/expose-css-module/package.json
  federated-css-react-ssr/expose-apps/expose-css/package.json
  federated-css-react-ssr/expose-apps/expose-jss/package.json
  federated-css-react-ssr/expose-apps/expose-less/package.json
  federated-css-react-ssr/expose-apps/expose-scss/package.json
  federated-css-react-ssr/expose-apps/expose-styled-component/package.json
  federated-css-react-ssr/expose-apps/expose-tailwind-css/package.json
  federated-css-react-ssr/shell-apps/css-jss/package.json
  federated-css-react-ssr/shell-apps/css-scss/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components-css-module/package.json
  federated-css-react-ssr/shell-apps/jss-styled-components/package.json
  federated-css-react-ssr/shell-apps/less-scss/package.json
  federated-css-react-ssr/shell-apps/scss-tailwind-css/package.json
  loadable-react-16/app1/package.json
  loadable-react-16/app2/package.json
  loadable-react-18/app1/package.json
  loadable-react-18/app2/package.json
  pnpm-lock.yaml
  react-16-17-18-ssr/remote1/package.json
  react-16-17-18-ssr/remote2/package.json
  react-16-17-18-ssr/shell/package.json
  react-18-code-splitting/app1/package.json
  react-18-code-splitting/app2/package.json
  react-18-server-2-server/app1/package.json
  react-18-server-2-server/app2/package.json
  react-18-ssr/remote1/package.json
  react-18-ssr/remote2/package.json
  react-18-ssr/shell/package.json
  runtime-plugins/remote-router/host/package.json
  runtime-plugins/remote-router/pnpm-lock.yaml
  server-side-rendering/remote1/package.json
  server-side-rendering/remote2/package.json
  server-side-rendering/shell/package.json
  styled-components/app1/package.json
  styled-components/app2/package.json
  typescript-react-monorepo-test/packages/host/package.json
  typescript-react-monorepo-test/packages/remote/package.json
  typescript-react-monorepo/packages/app1/package.json
  typescript-react-monorepo/packages/app2/package.json
  typescript-react-monorepo/packages/host/package.json
Labels: workflow-failure

#4223 chore(deps): update jest monorepo to v29 (major)
  medusa-nx-native-federation-example/package.json
  package.json
  pnpm-lock.yaml
Labels: workflow-success

#4224 chore(deps): update dependency postcss-preset-env to v9.6.0
  federated-library-from-cdn/app1/package.json
  federated-library-from-cdn/app2/package.json
  federated-library-from-cdn/remoteLibrary/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4225 chore(deps): update node.js to v22
  dashboard-admin-react-rspack-material-ui/dashboard-app/Dockerfile
  dashboard-admin-react-rspack-material-ui/dashboard-app/Dockerfile.dev
  dashboard-admin-react-rspack-material-ui/faq-app/Dockerfile
  dashboard-admin-react-rspack-material-ui/faq-app/Dockerfile.dev
  dashboard-admin-react-rspack-material-ui/root/Dockerfile
  dashboard-admin-react-rspack-material-ui/root/Dockerfile.dev
  dashboard-admin-react-rspack-material-ui/sidebar/Dockerfile
  dashboard-admin-react-rspack-material-ui/sidebar/Dockerfile.dev
  dashboard-admin-react-rspack-material-ui/team-app/Dockerfile
  dashboard-admin-react-rspack-material-ui/team-app/Dockerfile.dev
Labels: workflow-success

#4237 fix(deps): update dependency @module-federation/utilities to v3
  pnpm-lock.yaml
  react-storybook/host/package.json
  typescript-react-fallback/app1/package.json
Labels: workflow-success

#4238 fix(deps): update dependency @mui/x-data-grid to v7
  dashboard-admin-react-rspack-material-ui/team-app/package.json
  pnpm-lock.yaml
Labels: workflow-success

#4247 fix: rspack ssr modernjs ssr live reload
  modernjs-ssr/dynamic-provider/package.json
  modernjs-ssr/host/package.json
  modernjs-ssr/host/src/routes/page.tsx
  modernjs-ssr/provider/package.json
  pnpm-lock.yaml
Labels: workflow-success
